# Generated by Django 5.0.6 on 2024-06-03 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('work_sec', models.PositiveIntegerField(default=30, help_text='Minimum 30 seconds', verbose_name='Work Seconds')),
                ('avg_sec', models.PositiveIntegerField(default=30, help_text='Minimum 30 seconds', verbose_name='Average Seconds')),
                ('num_users', models.PositiveIntegerField(verbose_name='Number of Users')),
                ('reached_users', models.PositiveIntegerField(default=0, verbose_name='Reached Users')),
                ('order_schedule', models.DateTimeField(blank=True, null=True, verbose_name='Order Schedule')),
                ('domain_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=10, verbose_name='Domain Type')),
                ('action', models.CharField(blank=True, choices=[('Sponsored', 'Sponsored'), ('Business', 'Business'), ('Sponsored Business', 'Sponsored Business')], max_length=100, null=True)),
                ('second_action', models.CharField(blank=True, choices=[('website', 'Website'), ('direction', 'Direction'), ('call', 'Call')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=255)),
                ('UserAgent', models.CharField(max_length=255)),
                ('domain_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=10, verbose_name='Domain Type')),
                ('inUsed', models.BooleanField(default=False)),
                ('last_fetched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyDetail',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.profile')),
                ('status', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('regionName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=200)),
                ('proxyusername', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_sponsored', models.BooleanField(default=False)),
                ('has_business', models.BooleanField(default=False)),
                ('has_sponsored_business', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Waiting', max_length=100)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='serverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.servertable'),
        ),
    ]
