# Generated by Django 4.2.11 on 2024-06-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='click_domain_only',
            field=models.BooleanField(default=False),
        ),
    ]
