# Generated by Django 4.2.11 on 2024-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_click_domain_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_business_or_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='click_domain_only',
            field=models.BooleanField(default=False, verbose_name='Click domain only'),
        ),
    ]
